<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <RootNamespace>Aspose.Pdf.Examples.CSharp</RootNamespace>
    <AssemblyName>Aspose.Pdf.Examples.CSharp</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject>Aspose.Pdf.Examples.CSharp.Examples</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspose.Cells" Version="25.11.0" />
    <PackageReference Include="Aspose.PDF" Version="25.11.0" />
    <PackageReference Include="DotNetZip.Reduced" Version="1.9.1.8" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="2.1.0" />
  </ItemGroup>
</Project>